export const GET_ALL_VIDEOGAMES = "GET_ALL_VIDEOGAME";
export const GET_DETAIL_VIDEOGAME = "GET_DETAIL_VIDEOGAME";
export const GET_ALL_GENRES = "GET_ALL_GENRES"
export const CLEAN_DETAIL = "CLEAN_DETAIL";
export const FILTER_BY_SOURCE = "FILTER_BY_SOURCE";
export const SEARCH_VIDEOGAMES = "SEARCH_VIDEOGAMES";
export const ORDER_VIDEOGAMES = "ORDER_VIDEOGAMES";
export const POST_VIDEOGAMES = "POST_VIDEOGAMES";

/* import { GET_ALL_VIDEOGAMES,
    GET_DETAIL_VIDEOGAME,
    GET_ALL_GENRES,
    CLEAN_DETAIL,
    FILTER_BY_GENRE,
    FILTER_BY_SOURCE,
    SEARCH_VIDEOGAMES,
    ORDER_VIDEOGAMES,
    POST_VIDEOGAMES } from "./actionTypes"; */