export const GET_ALL_VIDEOGAMES = "GET_ALL_VIDEOGAME";
export const GET_DETAIL_VIDEOGAME = "GET_DETAIL_VIDEOGAME";
export const CLEAN_DETAIL = "CLEAN_DETAIL";
export const GET_ALL_GENRES = "GET_ALL_GENRES"
export const GET_BY_NAME = "GET_BY_NAME";
export const FILTER_BY_GENRE = "FILTER_BY_GENRE";
export const FILTER_BY_ALPHA = " ORD_ALPHA";
export const FILTER_ALPHA_REV = " ORD_ALPHA_REV";
export const FILTER_BY_PLATFORMS = "ORD_BY_PLATFORMS";
export const FILTER_BY_RATING = "ORD_BY_RATING";
export const POST_VIDEOGAMES = "POST_VIDEOGAMES";

/* GET_ALL_VIDEOGAMES,
    GET_DETAIL_VIDEOGAME,
    CLEAN_DETAIL,
    GET_ALL_GENRES,
    GET_BY_NAME,
    FILTER_BY_GENRE,
    FILTER_BY_ALPHA,
    FILTER_BY_PLATFORMS,
    FILTER_BY_PLATFORMS,
    FILTER_BY_RATING,
    POST_VIDEOGAMES  */